source "https://rubygems.org"

ruby "3.2.6"

gem "rails", "~> 7.1.6"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1.7"
gem "jwt"
gem "rack-cors"
gem "image_processing", "~> 1.2"
gem "rack-attack" # Rate limiting
gem "sidekiq" # Background job processing
gem "redis" # Required for Sidekiq and caching
gem "aws-sdk-s3", require: false # AWS S3 for Active Storage
gem "sentry-ruby" # Error tracking
gem "sentry-rails" # Sentry integration for Rails
gem "newrelic_rpm" # Application performance monitoring

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "dotenv-rails"
  gem "rspec-rails", "~> 6.0" # Testing framework
  gem "factory_bot_rails" # Test data factories
  gem "rswag" # Swagger/OpenAPI documentation
  gem "rswag-api" # Swagger API endpoint
  gem "rswag-ui" # Swagger UI
end

group :test do
  gem "shoulda-matchers", "~> 6.0" # Matchers for RSpec
  gem "simplecov", require: false # Code coverage
end

group :development do
  gem "listen", "~> 3.3"
  gem "wdm", ">= 0.1.0" if Gem.win_platform?
end

